# Generated by Django 6.0.1 on 2026-01-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='new', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_data', models.JSONField(blank=True, default=dict)),
                ('participants', models.JSONField(blank=True, default=list)),
                ('files_data', models.JSONField(blank=True, default=list)),
                ('analysis_result', models.JSONField(blank=True, default=dict)),
                ('simulation_data', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
