# Generated by Django 6.0.1 on 2026-01-24 10:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='case',
            name='client_name',
            field=models.CharField(blank=True, help_text='Himoya qilinayotgan shaxs F.I.O', max_length=255),
        ),
        migrations.AddField(
            model_name='case',
            name='client_role',
            field=models.CharField(blank=True, help_text="Masalan: Da'vogar, Javobgar, Sudlanuvchi, Jabrlanuvchi, Guvoh, Boshqa", max_length=100),
        ),
        migrations.AddField(
            model_name='case',
            name='court_stage',
            field=models.CharField(blank=True, help_text='Masalan: Tergov, Birinchi instansiya, Apellyatsiya, Kassatsiya, Nazorat tartibida', max_length=100),
        ),
        migrations.AddField(
            model_name='case',
            name='court_type',
            field=models.CharField(blank=True, help_text="Masalan: Fuqarolik, Jinoyat, Ma'muriy, Iqtisodiy", max_length=100),
        ),
        migrations.AddField(
            model_name='case',
            name='deadline',
            field=models.DateField(blank=True, help_text="Asosiy muddat (agar mavjud bo'lsa)", null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='folder',
            field=models.CharField(blank=True, default='', help_text='Masalan: Faol, Arxivlangan, Muzlatilgan', max_length=50),
        ),
        migrations.AddField(
            model_name='case',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(default='new', help_text='Masalan: new, processing, completed', max_length=50),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['user', 'created_at'], name='cases_case_user_id_b50ac9_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['user', 'status'], name='cases_case_user_id_ebe4e2_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['user', 'folder'], name='cases_case_user_id_f59c2f_idx'),
        ),
    ]
